### ISSUE TITLE
Controls for fields involving numbers? And other "standard" fields?

### ISSUE THREAD

**Issue by sarahfathallah** [codefordc/districthousing#169]
This is more of a nice to have, but to avoid data entry errors, is it possible to control the content in the fields involving numbers? e.g.:
- Phone numbers should have 10 digits
- Similar idea for SSN, driver license numbers, zip codes, etc.

Same goes for fields like e-mail addresses (check if format is correct), maybe others.

**Comment by jrunningen** [comment]
I'm cautious about field validation because it's easy to make it too restrictive.  For example, 
* Foreign phone numbers might have more than 10 digits.
* Driver's license number formats are different for every state.
* Email can *mostly* be validated with the following regular expression, but it's ridiculous: 
```
[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?`
```
And since the data is just being pasted verbatim into some PDFs, and not, say, used to send automated e-mails or make phone calls, it seems safer to me to just accept whatever the user wants to give us, for the most part.

**Comment by jrunningen** [comment]
Maybe we could warn the user if the field looks weird, but let them use it anyway.

**Comment by mlouie** [comment]
I'm going to close this, because we need more requirements on what types of validation we will do.  When we get specific requirements for a particular field, we will open a new ticket and describe the requirements for the field.
