### ISSUE TITLE
Document mapping between fields in Bread's Salesforce objects and our app

### ISSUE THREAD

**Issue by mlouie** [codefordc/districthousing#184]
We should document the mapping between Bread for the City's Salesforce instance and the fields that are used in the online form provided by our application.  This will also help us understand  which fields should be added to Bread for the City's Salesforce.

**Comment by mlouie** [comment]
I started this spreadsheet for us: https://docs.google.com/spreadsheets/d/1okmV95DiF-LDXNC6VyAHQHYSR4eAZqaqKJUQyFcgZhE/edit#gid=0

**Comment by jrunningen** [comment]
I've updated the spreadsheet accordingly.  It turns out the Salesforce model is not nearly as complete as our database schema, and most of the information we gather is simply not present in Salesforce.

I make that claim based on looking through the names of the salesforce fields as documented in https://github.com/codefordc/districthousing/blob/master/test/fake_intake.rb.

**Comment by sarahfathallah** [comment]
Yes, the Salesforce is intended to capture intake information for all Bread for the City clients, including clients of services other than the Housing Program (which may not require this level of detail).

**Comment by mlouie** [comment]
I spoke with Stacey and Andrew on Wednesay last week.  They want to use
Salesforce as the system of record for all of this information, so they are
going to modify Salesforce to capture everything.

The are now asking if we can write information we collect in our forms back
to Salesforce.  I think this is a great nod of approval for the forms your
created, Jeff. :) I'll investigate the technical implementation.  I suspect
it should be straightforward w/ the Salesforce gem we're using.
