### ISSUE TITLE
Update database seed to load project-based section 8 buildings and their lat/longs

### ISSUE THREAD

**Issue by mlouie** [codefordc/districthousing#186]
We now have project-based section 8 buildings that are geocoded.  If we're going to do any mapping with this data or expose an API endpoint for others to do interesting things with the building data, we'll want to load this data into our database.  I think this should go in the seed file.

Geocoded data: 
https://docs.google.com/spreadsheets/d/1xd9UcFg2AvKMmTN6gceI5A7b_UfYa13voFBj5R0lNTQ/edit#gid=1512093904

Big hat tip to @lizhaney for providing the building data and @evonfriedland for geocoding it.

**Comment by evonfriedland** [comment]
Just an fyi, the following file provides many updates to the original section 8 housing dataset (including other affordable housing units) and includes additional information on building management and walkscores for all locations (as per the recent email https://groups.google.com/forum/#!topic/affordable-housing-brigade/1fhb9KYkHd0):

https://docs.google.com/spreadsheets/d/1_8cvLSUjx2kdUtoWLesf4n_af7tNsEoO3RoSewCIGPw/

So this one should be used instead. Others should feel free to submit corrections to that dataset if they find any errors/missing information.

**Comment by evonfriedland** [comment]
Some things that would be useful to check are non-profit status of owners (I think there are some errors and possible inconsistencies there. Building ownership isn't always easy to check, because companies form individual LLCs, etc. for each building.), subsidy dates, and any missing management info. The management info will be helpful if we end up wanting to do outreach to them re: implementing a standardized application and/or securing pdf applications, since they're the ones that choose application requirements.

**Comment by evonfriedland** [comment]
Working on this
