### ISSUE TITLE
Do This

### ISSUE THREAD

**Issue by bigyehooda** [codefordc/districthousing#258]
![new ui](https://cloud.githubusercontent.com/assets/8889566/6384267/756a2386-bd28-11e4-88f4-a8e801acec79.png)

**Comment by kevko** [comment]
+1000000000000

**Comment by mlouie** [comment]
Example: http://www.jqueryscript.net/demo/Animated-Vertical-Accordion-Menu-with-jQuery-CSS3-mtree-js/#

**Comment by mlouie** [comment]
More examples: http://cssmenumaker.com/blog/5-free-jquery-accordion-menus

**Comment by uncompiled** [comment]
Like this?  

![image](https://cloud.githubusercontent.com/assets/408989/7080390/455ce4d2-deff-11e4-94dd-1c2ddb3f0162.png)

**Comment by emanuelfeld** [comment]
Yes! You perfectly capture my drawing's likeness.

**Comment by emanuelfeld** [comment]
We might want to do something about the top progress bar. It's not super clear what it refers to.

**Comment by uncompiled** [comment]
What do you think about removing the progress bar and putting a percentage badge next to the title?

![image](https://cloud.githubusercontent.com/assets/408989/7099680/60c00e48-dfc7-11e4-9d3b-97afe96caee3.png)

**Comment by emanuelfeld** [comment]
Better, I think. We might also want to right justify the counts in the accordion, so that they're next to the dropdown arrows and also visually distinguish the counts from the percentages. 

Should we remove the percentage statistic next to 'Client'? It seems odd that we would have a percentage there and counts for all the other section headings.

**Comment by uncompiled** [comment]
I agree with right justifying the counts. It also makes it easier to read.

Regarding the percentage statistic, I left it there because it was part of the original tab, but I think it should be removed from the section header to be consistent with the information in the other section headers.

![image](https://cloud.githubusercontent.com/assets/408989/7101647/269f1578-e031-11e4-8c80-b81f750de90c.png)

**Comment by jrunningen** [comment]
I'm looking forward to this pull request!

**Comment by emanuelfeld** [comment]
Much, much better. Thanks @uncompiled!

**Comment by emanuelfeld** [comment]
@uncompiled Just noticed the dropdown arrow appeared on the 'Client' section. There are no sub-elements to Client, though, right?

**Comment by uncompiled** [comment]
No, there aren't any sub-elements for Client. It will be removed.
