### ISSUE TITLE
Logic Error: "Household Member Count"

### ISSUE THREAD

**Issue by jposi** [codefordc/districthousing#301]
When you click to create a new applicant, household member count is listed as size including yourself. However, when you enter someone with a household size of 1, a user is prompted to add information about their additional household member, even though the HH size is one.

Please fix it so that a household size of 1 does not prompt for add'l HH members. 
(please let me know if this isn't clear)

**Comment by emanuelfeld** [comment]
We could also just change it to "What is the total number of people in your household, not including yourself?"

**Comment by jposi** [comment]
It's not a matter of how the question is asked - the question is asked
properly, but when you fill out household size of 1, the program asks for
an additional HH members information - that just needs to be removed.

**Comment by emanuelfeld** [comment]
It sounds to me like it's not being asked correctly, because when you input a household size of 1 it interprets that as meaning there is 1 additional householder member, other than yourself (and then asks for that other household member's info). The way it's currently structured, if you are the only person in your household you should input 0 in that box, not 1.

Unless I'm not understanding the issue.
