### ISSUE TITLE
.pdf Hedin House, student status is not showing up

### ISSUE THREAD

**Issue by mlouie** [codefordc/districthousing#309]
When student status is collected in the online form, it's not being reflected in the PDF version.  Look at page 3 of the application.

**Comment by jrunningen** [comment]
Hedin House's student field names are shown here:

$ pdftk public/forms/Hedin_House.pdf dump_data_fields | grep -i student
FieldName: StudentY
FieldName: StudentN
FieldName: HH1StudentY
FieldName: HH1StudentN
FieldName: HH2StudentY
FieldName: HH2StudentN
FieldName: HH3StudentY
FieldName: HH3StudentN
FieldName: HH4StudentY
FieldName: HH4StudentN
FieldName: HH5StudentY
FieldName: HH5StudentN
FieldName: HH6StudentY
FieldName: HH6StudentN
FieldName: HH7StudentY
FieldName: HH7StudentN
FieldName: HH8StudentY
FieldName: HH8StudentN

The code looks for "StudentStatus" instead of "Student".

More importantly, page 3 of Hedin House asks questions like "Are you or any other adult household member..."  The current dictionary doesn't have a syntax for saying "Does this apply to anyone?"  We'd have to add that to answer these questions correctly.

**Comment by lizhaney** [comment]
Re: Student Status. These are tickboxes to answer the question, Are you a full or part time student? Student Status returns Full-time, Part-time.  My suggestion would be to code it as

StudentStatusTickYes
StudentStatusTickNo

Wherein if a part time OR full time student, it'd render a yes. I'm not particular about the naming.

Jeff, Marcus, thoughts?

**Comment by jrunningen** [comment]
Yes, I think that would solve the tickbox issue.

**Comment by adinneen** [comment]
@emanuelfeld Issue #309 should be closed.  I updated this form https://drive.google.com/open?id=0B8rQX6ajIoEMd2FBdXFrRGE1RUE.  So that the student status on Page 3 is changed from StudentY/StudentN to StudentStatusTickYes/StudentStatusTickNo
