### ISSUE TITLE
Residence Address: Add Homeless

### ISSUE THREAD

**Issue by jposi** [codefordc/districthousing#311]
Stacey wants to be able to write "Homeless" on Residence Address. Just typing in "homeless" produces an error - it does not save. However, if Stacey adds Washington, DC, Zip, then it saves. That's inaccurate.

Not sure what the fix is - need to investigate.

**Comment by emanuelfeld** [comment]
Do any of the application pdfs incorporate homelessness?

**Comment by jrunningen** [comment]
![homeless](https://cloud.githubusercontent.com/assets/1123795/7577819/cd2ca508-f81a-11e4-8524-26ba099da450.png)

This seems to save when I try it.  Were you doing something different?

**Comment by uncompiled** [comment]
Testing this, I was able to save with Homeless:
![homeless](https://cloud.githubusercontent.com/assets/408989/8097440/38c205ae-0fb0-11e5-8d91-9152639d47b4.png)

However, the Residence title doesn't work unless there is a city added. Would it make sense to validate the street address and display "Homeless" instead of "Residence at"?

**Comment by jrunningen** [comment]
Yes, that should be a simple edit for someone to make in the address model.

**Comment by colinxfleming** [comment]
Hey, I'm working on this in a fork. After I install the pdftk dependency I'll make this edit. 

I couldn't recreate the not saving issue, but I'll make the display fix.
