### ISSUE TITLE
Print 'None' on PDFs for Employment information if no information is given

### ISSUE THREAD

**Issue by mlouie** [codefordc/districthousing#312]
Case workers wants the applications to be explicit about not having an employment history vs forgetting to add that information.

**Comment by jrunningen** [comment]
Which field name should say "None"?  It might be reasonable to do this with either JobTitle, JobEmployer, or both.

**Comment by meiao** [comment]
Hey guys.
I just committed to my repo (above linked) a suggestion on how to handle this.
Basically it adds a "magic" suffix "_or_none" that any variable that has that suffix and has no value will display None.

I haven't made the pull request because I want to test it before adding to the main repo.

And I was thinking, maybe we could go even further and add a rule that any variable with "_or_xxx" would display xxx if it has no value.

**Comment by meiao** [comment]
Nevermind, my code does not work. I was trying to achieve the Ballmer's peak that night.
Did not work so well.
Will try to work more on it.

**Comment by meiao** [comment]
Ok, a new commit, with Jeff's correction, made the "None" stuff work.
What do you guys think of it?
What about the _or_xxx alternative? Which do you think would be better?
