### ISSUE TITLE
[PDF]: Samuel Kelsey Page 1: Demographic information changes

### ISSUE THREAD

**Issue by mlouie** [codefordc/districthousing#370]
From Stacey:

- The Current Address should be the mailing address (it's pulling the residence address).
- The phone number is not populating.
- The contact peoples' addresses are not populating.
- The Ethnicity checkbox is not checked (the Race one is good).

**Comment by charleshuang80** [comment]
Made fixes on Page 1:
- Fixed current address to pull mailing address
- Fixed Phone Number. This is currently pulling the Home Phone Number. I think we should check with Stacey that this is the right number to pull (I remember from the meeting they might want Preferred Number or a different one to pull as default).
- Fixed contact peoples' addresses
- Fixed Ethnicity tickboxes.

Uploaded changes to Samuel Kelsey Apartments pdf form in formsync (needed to add 2 versions because missed contact people's addresses first time around).

Should be able to be closed. Please check and let me know.

**Comment by mlouie** [comment]
Thank you, @charleshuang80!
